### ISSUE TITLE
About checkpoint file header structure

### ISSUE THREAD

**Issue by YuLin9568** [biklooost/PROPhet#3]
Hi, 
I test the tutorial data, and successfully generate the potential_C(input: structure, output: energy).
But I confuse about the parameter in the potential_C, 
the output(energy) mean is "0", and the output(energy) variance is "1". (file shown as below)
[potential_C.txt](https://github.com/biklooost/PROPhet/files/1557891/potential_C.txt)
If these values are correct, please tell me the reason or give me the reference.

Thanks.

**Comment by levilentz** [comment]
Hello,

PROPhet does preprocessing of the data to ease training. Those two values are there because we eventually want to build out PROPhet to be able to arbitrarily shift the data. However, as it is now, if you perform output preconditioning, it will shift the data to have mean 0 and variance 1. This is very common in machine learning methods. 

Sorry for the delay! 

Cheers,

Levi
